# Generated by Django 3.0.1 on 2020-02-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barem', '0086_auto_20200127_1016'),
        ('client', '0002_client_barem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='barem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barems', to='barem.Barem'),
        ),
    ]
