# Generated by Django 3.0.1 on 2020-02-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200202_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='raison_social',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Raison Social'),
        ),
    ]
