# Generated by Django 3.0.1 on 2020-02-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200222_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
