# Generated by Django 3.0.1 on 2020-03-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200224_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
