# Generated by Django 3.0.1 on 2020-05-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginecapacity',
            name='unit',
            field=models.CharField(choices=[('T', 'T'), ('M', 'M')], max_length=5, verbose_name='Unité'),
        ),
    ]
