# Generated by Django 3.0.1 on 2020-05-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_auto_20200508_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginecapacity',
            name='unit',
            field=models.CharField(choices=[('T', 'T'), ('M', 'M')], default='T', max_length=5, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='enginecapacity',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=4, unique=True, verbose_name='Capacité'),
        ),
    ]
