# Generated by Django 3.0.1 on 2020-05-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_auto_20200508_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginecapacity',
            name='value',
            field=models.FloatField(verbose_name='Capacité'),
        ),
        migrations.AlterUniqueTogether(
            name='enginecapacity',
            unique_together={('unit', 'value')},
        ),
    ]
