# Generated by Django 3.0.1 on 2020-05-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_auto_20200508_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='capacity',
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capacities', to='park.EngineCapacity')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='park.EngineType')),
            ],
        ),
        migrations.AlterField(
            model_name='engine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='park.EngineModel'),
        ),
    ]
