# Generated by Django 3.0.1 on 2020-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_auto_20200508_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaufeur',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='chaufeur',
            name='can_drive',
            field=models.ManyToManyField(to='park.EngineType'),
        ),
        migrations.AddField(
            model_name='engine',
            name='marque',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='nature',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='year',
            field=models.IntegerField(null=True, verbose_name='année'),
        ),
    ]
