# Generated by Django 3.0.1 on 2020-05-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_auto_20200508_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginemodel',
            name='etat',
            field=models.CharField(choices=[('service', 'En service'), ('horsservice', 'Hors service')], default='service', max_length=100),
        ),
    ]
