# Generated by Django 3.0.1 on 2020-05-09 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0009_enginemodel_etat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enginemodel',
            old_name='etat',
            new_name='state',
        ),
    ]
